[build]
  publish = "/"
  command = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "/"
    exclude = [
      '**/404.html'
    ]

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    # Check external links
    skipPatterns = [
      "mailto:*"
    ]
